version: 2.1

orbs:
  snyk: snyk/snyk@2.2.0

jobs:
 build:
   docker:
     - image: circleci/node:16.0.0
   steps:
     - checkout
     - run: npm install -q
     - snyk/scan:
          token-variable: SNYK_TOKEN